#!/usr/bin/env node
/* Regenerates src/fonts/fonts-base64.js and src/metrics.js from the TTFs in
   src/fonts/. Run after changing a font:
       node tools/build-fonts.js

   jsPDF can only embed TrueType (glyf) outlines. If a font arrives as a CFF
   OpenType file (magic "OTTO", e.g. the Akira Expanded demo), convert it first:
       pip install fonttools
       python3 tools/otf2ttf.py "in.otf" src/fonts/out.ttf

   FONTS below maps the window.DF_FONTS key -> filename. DISPLAY_FONT is the
   proportional face whose advance widths get baked into metrics.js; every other
   face is assumed monospaced at MONO_ADVANCE. */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DIR = path.join(ROOT, 'src/fonts');

const FONTS = {
  AKIRA_EXPANDED: 'AkiraExpanded.ttf',
  JETBRAINS_MONO: 'JetBrainsMono-Regular.ttf'
};
const DISPLAY_FONT = 'AkiraExpanded.ttf';
const MONO_FONT = 'JetBrainsMono-Regular.ttf';
const CHARSET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ 0123456789';

/* ---- minimal TTF reader: head/hhea/hmtx/cmap(format 4)/OS-2 ---- */
const u16 = (b, o) => b.readUInt16BE(o);
const u32 = (b, o) => b.readUInt32BE(o);
const i16 = (b, o) => b.readInt16BE(o);

function tableDir(b) {
  const n = u16(b, 4), t = {};
  for (let i = 0; i < n; i++) {
    const o = 12 + 16 * i;
    t[b.toString('latin1', o, o + 4)] = { off: u32(b, o + 8), len: u32(b, o + 12) };
  }
  return t;
}

function cmapLookup(b, off) {
  const n = u16(b, off + 2);
  let sub = null;
  for (let i = 0; i < n; i++) {
    const o = off + 4 + 8 * i, p = u16(b, o), e = u16(b, o + 2);
    if ((p === 3 && (e === 1 || e === 0)) || p === 0) sub = off + u32(b, o + 4);
  }
  if (sub === null || u16(b, sub) !== 4) throw new Error('no format-4 cmap subtable');
  const segX2 = u16(b, sub + 6), seg = segX2 / 2;
  const endO = sub + 14, startO = endO + segX2 + 2,
    deltaO = startO + segX2, rangeO = deltaO + segX2;
  return function (cp) {
    for (let s = 0; s < seg; s++) {
      if (cp > u16(b, endO + 2 * s)) continue;
      const start = u16(b, startO + 2 * s);
      if (cp < start) return 0;
      const delta = i16(b, deltaO + 2 * s), ro = u16(b, rangeO + 2 * s);
      if (ro === 0) return (cp + delta) & 0xffff;
      const gi = u16(b, rangeO + 2 * s + ro + 2 * (cp - start));
      return gi === 0 ? 0 : (gi + delta) & 0xffff;
    }
    return 0;
  };
}

function readFont(file) {
  const b = fs.readFileSync(path.join(DIR, file));
  if (b.toString('latin1', 0, 4) === 'OTTO') {
    throw new Error(file + ' is a CFF OpenType font; convert it to TTF first ' +
      '(see the header of this script) — jsPDF cannot embed CFF outlines.');
  }
  const t = tableDir(b);
  const upem = u16(b, t.head.off + 18);
  const numH = u16(b, t.hhea.off + 34);
  const look = cmapLookup(b, t.cmap.off);
  const os2 = t['OS/2'].off;
  const capHeight = u16(b, os2) >= 2 ? i16(b, os2 + 88) / upem : null;
  const widths = {};
  for (const ch of CHARSET) {
    const g = look(ch.codePointAt(0));
    widths[ch] = +(u16(b, t.hmtx.off + 4 * Math.min(g, numH - 1)) / upem).toFixed(5);
  }
  return { buf: b, upem, capHeight, widths };
}

/* ---- emit ---- */
const loaded = {};
for (const [key, file] of Object.entries(FONTS)) loaded[file] = readFont(file);

let out = '// Generated by tools/build-fonts.js. Do not hand-edit.\n';
out += '// Akira Expanded is converted from the supplied CFF/OpenType demo to\n';
out += '// TrueType outlines, because jsPDF can only embed glyf-flavoured fonts.\n';
for (const [k, v] of Object.entries(FONTS)) out += '//   ' + k + ' = ' + v + '\n';
out += '\nwindow.DF_FONTS = {\n';
out += Object.entries(FONTS)
  .map(([k, v]) => '  ' + k + ': "' + loaded[v].buf.toString('base64') + '"')
  .join(',\n');
out += '\n};\n';
fs.writeFileSync(path.join(DIR, 'fonts-base64.js'), out);

const disp = loaded[DISPLAY_FONT], mono = loaded[MONO_FONT];
const monoAdv = mono.widths['M'];
const uneven = Object.entries(mono.widths).filter(([, w]) => Math.abs(w - monoAdv) > 1e-6);
if (uneven.length) throw new Error(MONO_FONT + ' is not monospaced: ' + JSON.stringify(uneven.slice(0, 4)));

let m = '/* metrics.js — generated by tools/build-fonts.js. Do not hand-edit.\n';
m += '   Advance widths in em, so the preview and the PDF measure text identically\n';
m += '   instead of each asking its own font engine. */\n';
m += 'window.DFMetrics = {\n';
m += '  // ' + MONO_FONT + ' is monospaced: every glyph advances ' + monoAdv + 'em.\n';
m += '  MONO_ADVANCE: ' + monoAdv + ',\n';
m += '  CAP_HEIGHT: { display: ' + disp.capHeight + ', mono: ' + mono.capHeight + ' },\n';
m += '  // ' + DISPLAY_FONT + ', uppercase + digits (the month name is the only\n';
m += '  // proportional text on the sheet).\n';
m += '  DISPLAY: ' + JSON.stringify(disp.widths) + '\n';
m += '};\n';
fs.writeFileSync(path.join(ROOT, 'src/metrics.js'), m);

console.log('wrote src/fonts/fonts-base64.js (' +
  (fs.statSync(path.join(DIR, 'fonts-base64.js')).size / 1024).toFixed(0) + 'KB)');
console.log('wrote src/metrics.js  | mono advance ' + monoAdv +
  'em | cap heights display ' + disp.capHeight + ' mono ' + mono.capHeight);
