/* metrics.js — generated by tools/build-fonts.js. Do not hand-edit.
   Advance widths in em, so the preview and the PDF measure text identically
   instead of each asking its own font engine. */
window.DFMetrics = {
  // JetBrainsMono-Regular.ttf is monospaced: every glyph advances 0.6em.
  MONO_ADVANCE: 0.6,
  CAP_HEIGHT: { display: 0.7001953125, mono: 0.73 },
  // AkiraExpanded.ttf, uppercase + digits (the month name is the only
  // proportional text on the sheet).
  DISPLAY: {"0":0.85205,"1":0.72363,"2":0.85205,"3":0.85205,"4":0.85205,"5":0.85205,"6":0.85205,"7":0.7876,"8":0.85205,"9":0.85205,"A":1.02783,"B":0.8999,"C":0.91455,"D":0.91602,"E":0.7876,"F":0.81982,"G":0.91162,"H":0.91602,"I":0.27539,"J":0.91553,"K":0.96387,"L":0.7876,"M":1.17188,"N":0.91602,"O":0.91553,"P":0.8999,"Q":0.91602,"R":0.8999,"S":0.91016,"T":0.88379,"U":0.91602,"V":0.99609,"W":1.49219,"X":1.02783,"Y":1.01172,"Z":0.86768," ":0.48828}
};
